<a href="https://colab.research.google.com/github/Rukawuba/4GeeksAcademy/blob/master/LA_Clippers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:

import pandas as pd

# Assuming your JSON file is named 'data.json' and is in the current directory
players_df = pd.read_json('player.json')

# Now you can work with the data in the 'df' DataFrame
players_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 480 entries, 0 to 479
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   player_id   480 non-null    int64
 1   first_name  480 non-null    object
 2   last_name   480 non-null    object
dtypes: int64(1), object(2)
memory usage: 11.4+ KB

In [7]:
games_df = pd.read_json('game_schedule.json')
games_df

,game_id,home_id,home_score,away_id,away_score,game_date
0,1,1610612752,112,1610612750,106,2024-01-01 15:00:00
1,2,1610612761,124,1610612739,121,2024-01-01 19:30:00
2,3,1610612745,136,1610612765,113,2024-01-01 20:00:00
3,4,1610612749,113,1610612754,122,2024-01-01 20:00:00
4,5,1610612743,111,1610612766,93,2024-01-01 21:00:00
...,...,...,...,...,...,...
226,227,1610612750,121,1610612742,87,2024-01-31 20:00:00
227,228,1610612760,105,1610612743,100,2024-01-31 20:00:00
228,229,1610612759,98,1610612753,108,2024-01-31 20:00:00
229,230,1610612751,120,1610612756,136,2024-01-31 20:30:00
230,231,1610612757,119,1610612749,116,2024-01-31 22:00:00

In [8]:
lineups_df = pd.read_json('lineup.json')
lineups_df.info()
lineups_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117040 entries, 0 to 117039
Data columns (total 7 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   team_id     117040 non-null  int64
 1   player_id   117040 non-null  int64
 2   lineup_num  117040 non-null  int64
 3   period      117040 non-null  int64
 4   time_in     117040 non-null  float64
 5   time_out    117040 non-null  float64
 6   game_id     117040 non-null  int64
dtypes: float64(2), int64(5)
memory usage: 6.3 MB

           team_id  player_id  lineup_num  period  time_in  time_out  game_id
0       1610612737    1629027           1       1    720.0     456.0       17
1       1610612737    1629027           2       1    456.0     456.0       17
2       1610612737    1629027           3       1    456.0     383.0       17
3       1610612737    1629027           9       1    189.0     165.0       17
4       1610612737    1629027          10       1    165.0     165.0       17
...            ...        ...         ...     ...      ...       ...      ...
117035  1610612759    1630572          54       4    234.0     234.0      121
117036  1610612759    1630572          55       4    234.0     234.0      121
117037  1610612759    1630572          56       4    234.0     183.0      121
117038  1610612759    1630572          57       4    183.0     183.0      121
117039  1610612759    1630572          58       4    183.0       0.0      121

[117040 rows x 7 columns]

In [9]:
roster_df = pd.read_json('roster.json')
roster_df.info()
roster_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   team_id        63 non-null     int64
 1   player_id      63 non-null     int64
 2   first_name     63 non-null     object
 3   last_name      63 non-null     object
 4   position       63 non-null     object
 5   contract_type  63 non-null     object
dtypes: int64(2), object(4)
memory usage: 3.1+ KB

       team_id  player_id first_name   last_name position contract_type
0   1610612737     202083     Wesley    Matthews       SG           NBA
1   1610612737     203991      Clint      Capela        C           NBA
2   1610612737     203992     Bogdan  Bogdanovic       SG           NBA
3   1610612737    1627749   Dejounte      Murray       PG           NBA
4   1610612737    1628981      Bruno    Fernando        C           NBA
..         ...        ...        ...         ...      ...           ...
58  1612709929    1641754       Seth       Lundy       SF       Two-Way
59  1612709929    1641812    Spencer     Rodgers       SG           GLG
60  1612709929    1641934      David   Singleton       SG           GLG
61  1612709929    1641935    Jarkell      Joiner       PG           GLG
62  1612709929    1641936      Miles      Norris       PF           GLG

[63 rows x 6 columns]

In [10]:
team_df = pd.read_json('team.json')
team_df.info()
team_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   teamId         62 non-null     int64
 1   leagueLk       62 non-null     object
 2   teamName       62 non-null     object
 3   teamNameShort  62 non-null     object
 4   teamNickname   62 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.5+ KB

        teamId leagueLk               teamName teamNameShort teamNickname
0   1610612737      NBA          Atlanta Hawks           ATL        Hawks
1   1610612738      NBA         Boston Celtics           BOS      Celtics
2   1610612739      NBA    Cleveland Cavaliers           CLE    Cavaliers
3   1610612740      NBA   New Orleans Pelicans           NOP     Pelicans
4   1610612741      NBA          Chicago Bulls           CHI        Bulls
..         ...      ...                    ...           ...          ...
57  1612709930      GLG        G League Ignite           GLI       Ignite
58  1612709931      GLG  Mexico City Capitanes           MXC    Capitanes
59  1612709932      GLG      Motor City Cruise           MCC       Cruise
60  1612709933      GLG         Rip City Remix           RCR        Remix
61  1612709934      GLG            Valley Suns           VAL         Suns

[62 rows x 5 columns]

In [11]:
team_affiliate_df = pd.read_json('team_affiliate.json')
team_affiliate_df.info()
team_affiliate_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   nba_teamId  30 non-null     int64
 1   nba_abrv    30 non-null     object
 2   glg_teamId  29 non-null     float64
 3   glg_abrv    29 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 1.1+ KB

    nba_teamId nba_abrv    glg_teamId glg_abrv
0   1610612737      ATL  1.612710e+09      CPS
1   1610612751      BKN  1.612710e+09      LIN
2   1610612738      BOS  1.612710e+09      MNE
3   1610612766      CHA  1.612710e+09      GBO
4   1610612741      CHI  1.612710e+09      WCB
5   1610612739      CLE  1.612710e+09      CLC
6   1610612742      DAL  1.612710e+09      TEX
7   1610612743      DEN  1.612710e+09      GRG
8   1610612765      DET  1.612710e+09      MCC
9   1610612744      GSW  1.612710e+09      SCW
10  1610612745      HOU  1.612710e+09      RGV
11  1610612754      IND  1.612710e+09      IMA
12  1610612746      LAC  1.612710e+09      ONT
13  1610612747      LAL  1.612710e+09      SBL
14  1610612763      MEM  1.612710e+09      MHU
15  1610612748      MIA  1.612710e+09      SXF
16  1610612749      MIL  1.612710e+09      WIS
17  1610612750      MIN  1.612710e+09      IWA
18  1610612740      NOP  1.612710e+09      BHM
19  1610612752      NYK  1.612710e+09      WES
20  1610612760      OKC  1.612710e+09      OKL
21  1610612753      ORL  1.612710e+09      OSC
22  1610612755      PHI  1.612710e+09      DEL
23  1610612756      PHX           NaN     None
24  1610612757      POR  1.612710e+09      RCR
25  1610612758      SAC  1.612710e+09      STO
26  1610612759      SAS  1.612710e+09      AUS
27  1610612761      TOR  1.612710e+09      RAP
28  1610612762      UTA  1.612710e+09      SLC
29  1610612764      WAS  1.612710e+09      CCG

In [12]:
lineups_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117040 entries, 0 to 117039
Data columns (total 7 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   team_id     117040 non-null  int64
 1   player_id   117040 non-null  int64
 2   lineup_num  117040 non-null  int64
 3   period      117040 non-null  int64
 4   time_in     117040 non-null  float64
 5   time_out    117040 non-null  float64
 6   game_id     117040 non-null  int64
dtypes: float64(2), int64(5)
memory usage: 6.3 MB

In [13]:
import pandas as pd
# Merge players and roster based on player_id
player_roster_df = pd.merge(players_df, roster_df, on='player_id', how='left')

In [14]:
player_roster_df

,player_id,first_name_x,last_name_x,team_id,first_name_y,last_name_y,position,contract_type
0,1626246,Boban,Marjanovic,NaN,NaN,NaN,NaN,NaN
1,1627742,Brandon,Ingram,NaN,NaN,NaN,NaN,NaN
2,1627749,Dejounte,Murray,1.610613e+09,Dejounte,Murray,PG,NBA
3,1627752,Taurean,Prince,NaN,NaN,NaN,NaN,NaN
4,1630164,James,Wiseman,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
479,203952,Andrew,Wiggins,NaN,NaN,NaN,NaN,NaN
480,203991,Clint,Capela,1.610613e+09,Clint,Capela,C,NBA
481,203932,Aaron,Gordon,NaN,NaN,NaN,NaN,NaN
482,1628978,Donte,DiVincenzo,NaN,NaN,NaN,NaN,NaN
483,1629028,Deandre,Ayton,NaN,NaN,NaN,NaN,NaN

In [16]:
# Merge player_roster with lineups based on roster_id
player_roster_lineup_df = pd.merge(player_roster_df, lineups_df, on='player_id', how='left')
player_roster_lineup_df

,player_id,first_name_x,last_name_x,team_id_x,first_name_y,last_name_y,position,contract_type,team_id_y,lineup_num,period,time_in,time_out,game_id
0,1626246,Boban,Marjanovic,NaN,NaN,NaN,NaN,NaN,1610612745,50,4,405.0,405.0,183
1,1626246,Boban,Marjanovic,NaN,NaN,NaN,NaN,NaN,1610612745,51,4,405.0,359.0,183
2,1626246,Boban,Marjanovic,NaN,NaN,NaN,NaN,NaN,1610612745,52,4,359.0,191.0,183
3,1626246,Boban,Marjanovic,NaN,NaN,NaN,NaN,NaN,1610612745,53,4,191.0,0.0,183
4,1626246,Boban,Marjanovic,NaN,NaN,NaN,NaN,NaN,1610612745,47,4,365.0,0.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117086,1629028,Deandre,Ayton,NaN,NaN,NaN,NaN,NaN,1610612757,50,4,5.6,4.6,231
117087,1629028,Deandre,Ayton,NaN,NaN,NaN,NaN,NaN,1610612757,51,4,4.6,4.6,231
117088,1629028,Deandre,Ayton,NaN,NaN,NaN,NaN,NaN,1610612757,52,4,4.6,2.8,231
117089,1629028,Deandre,Ayton,NaN,NaN,NaN,NaN,NaN,1610612757,53,4,2.8,2.8,231
117090,1629028,Deandre,Ayton,NaN,NaN,NaN,NaN,NaN,1610612757,54,4,2.8,0.0,231

In [18]:
# Merge with games based on game_id
player_roster_lineup_game_df = pd.merge(player_roster_lineup_df, games_df, on='game_id', how='left')
player_roster_lineup_game_df

,player_id,first_name_x,last_name_x,team_id_x,first_name_y,last_name_y,position,contract_type,team_id_y,lineup_num,period,time_in,time_out,game_id,home_id,home_score,away_id,away_score,game_date
0,1626246,Boban,Marjanovic,NaN,NaN,NaN,NaN,NaN,1610612745,50,4,405.0,405.0,183,1610612766,104,1610612745,138,2024-01-26 19:00:00
1,1626246,Boban,Marjanovic,NaN,NaN,NaN,NaN,NaN,1610612745,51,4,405.0,359.0,183,1610612766,104,1610612745,138,2024-01-26 19:00:00
2,1626246,Boban,Marjanovic,NaN,NaN,NaN,NaN,NaN,1610612745,52,4,359.0,191.0,183,1610612766,104,1610612745,138,2024-01-26 19:00:00
3,1626246,Boban,Marjanovic,NaN,NaN,NaN,NaN,NaN,1610612745,53,4,191.0,0.0,183,1610612766,104,1610612745,138,2024-01-26 19:00:00
4,1626246,Boban,Marjanovic,NaN,NaN,NaN,NaN,NaN,1610612745,47,4,365.0,0.0,3,1610612745,136,1610612765,113,2024-01-01 20:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117086,1629028,Deandre,Ayton,NaN,NaN,NaN,NaN,NaN,1610612757,50,4,5.6,4.6,231,1610612757,119,1610612749,116,2024-01-31 22:00:00
117087,1629028,Deandre,Ayton,NaN,NaN,NaN,NaN,NaN,1610612757,51,4,4.6,4.6,231,1610612757,119,1610612749,116,2024-01-31 22:00:00
117088,1629028,Deandre,Ayton,NaN,NaN,NaN,NaN,NaN,1610612757,52,4,4.6,2.8,231,1610612757,119,1610612749,116,2024-01-31 22:00:00
117089,1629028,Deandre,Ayton,NaN,NaN,NaN,NaN,NaN,1610612757,53,4,2.8,2.8,231,1610612757,119,1610612749,116,2024-01-31 22:00:00
117090,1629028,Deandre,Ayton,NaN,NaN,NaN,NaN,NaN,1610612757,54,4,2.8,0.0,231,1610612757,119,1610612749,116,2024-01-31 22:00:00

In [22]:
# prompt: I want to delete team_id_x and rename team_id_y to be team_id in the player_roster_lineup_game_df

# Delete team_id_x
player_roster_lineup_game_df = player_roster_lineup_game_df.drop('team_id_x', axis=1)

# Rename team_id_y to team_id
player_roster_lineup_game_df = player_roster_lineup_game_df.rename(columns={'team_id_y': 'team_id'})

player_roster_lineup_game_df.info()

KeyError: "['team_id_x'] not found in axis"

In [24]:
player_roster_lineup_game_df.info()
player_roster_lineup_game_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117091 entries, 0 to 117090
Data columns (total 18 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   player_id      117091 non-null  int64
 1   first_name_x   117091 non-null  object
 2   last_name_x    117091 non-null  object
 3   first_name_y   7278 non-null    object
 4   last_name_y    7278 non-null    object
 5   position       7278 non-null    object
 6   contract_type  7278 non-null    object
 7   team_id        117091 non-null  int64
 8   lineup_num     117091 non-null  int64
 9   period         117091 non-null  int64
 10  time_in        117091 non-null  float64
 11  time_out       117091 non-null  float64
 12  game_id        117091 non-null  int64
 13  home_id        117091 non-null  int64
 14  home_score     117091 non-null  int64
 15  away_id        117091 non-null  int64
 16  away_score     117091 non-null  int64
 17  game_date      117091 non-null  object
dtypes: float64(2), int64(9), object(7)
memory usage: 16.1+ MB

,player_id,first_name_x,last_name_x,first_name_y,last_name_y,position,contract_type,team_id,lineup_num,period,time_in,time_out,game_id,home_id,home_score,away_id,away_score,game_date
0,1626246,Boban,Marjanovic,NaN,NaN,NaN,NaN,1610612745,50,4,405.0,405.0,183,1610612766,104,1610612745,138,2024-01-26 19:00:00
1,1626246,Boban,Marjanovic,NaN,NaN,NaN,NaN,1610612745,51,4,405.0,359.0,183,1610612766,104,1610612745,138,2024-01-26 19:00:00
2,1626246,Boban,Marjanovic,NaN,NaN,NaN,NaN,1610612745,52,4,359.0,191.0,183,1610612766,104,1610612745,138,2024-01-26 19:00:00
3,1626246,Boban,Marjanovic,NaN,NaN,NaN,NaN,1610612745,53,4,191.0,0.0,183,1610612766,104,1610612745,138,2024-01-26 19:00:00
4,1626246,Boban,Marjanovic,NaN,NaN,NaN,NaN,1610612745,47,4,365.0,0.0,3,1610612745,136,1610612765,113,2024-01-01 20:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117086,1629028,Deandre,Ayton,NaN,NaN,NaN,NaN,1610612757,50,4,5.6,4.6,231,1610612757,119,1610612749,116,2024-01-31 22:00:00
117087,1629028,Deandre,Ayton,NaN,NaN,NaN,NaN,1610612757,51,4,4.6,4.6,231,1610612757,119,1610612749,116,2024-01-31 22:00:00
117088,1629028,Deandre,Ayton,NaN,NaN,NaN,NaN,1610612757,52,4,4.6,2.8,231,1610612757,119,1610612749,116,2024-01-31 22:00:00
117089,1629028,Deandre,Ayton,NaN,NaN,NaN,NaN,1610612757,53,4,2.8,2.8,231,1610612757,119,1610612749,116,2024-01-31 22:00:00
117090,1629028,Deandre,Ayton,NaN,NaN,NaN,NaN,1610612757,54,4,2.8,0.0,231,1610612757,119,1610612749,116,2024-01-31 22:00:00

In [25]:
player_roster_lineup_game_df = player_roster_lineup_game_df.drop(['first_name_y','last_name_y'], axis=1)

In [29]:
player_roster_lineup_game_df = player_roster_lineup_game_df.rename(columns={'team_id': 'teamId'})

In [30]:
player_roster_lineup_game_df

,player_id,first_name_x,last_name_x,position,contract_type,teamId,lineup_num,period,time_in,time_out,game_id,home_id,home_score,away_id,away_score,game_date
0,1626246,Boban,Marjanovic,NaN,NaN,1610612745,50,4,405.0,405.0,183,1610612766,104,1610612745,138,2024-01-26 19:00:00
1,1626246,Boban,Marjanovic,NaN,NaN,1610612745,51,4,405.0,359.0,183,1610612766,104,1610612745,138,2024-01-26 19:00:00
2,1626246,Boban,Marjanovic,NaN,NaN,1610612745,52,4,359.0,191.0,183,1610612766,104,1610612745,138,2024-01-26 19:00:00
3,1626246,Boban,Marjanovic,NaN,NaN,1610612745,53,4,191.0,0.0,183,1610612766,104,1610612745,138,2024-01-26 19:00:00
4,1626246,Boban,Marjanovic,NaN,NaN,1610612745,47,4,365.0,0.0,3,1610612745,136,1610612765,113,2024-01-01 20:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117086,1629028,Deandre,Ayton,NaN,NaN,1610612757,50,4,5.6,4.6,231,1610612757,119,1610612749,116,2024-01-31 22:00:00
117087,1629028,Deandre,Ayton,NaN,NaN,1610612757,51,4,4.6,4.6,231,1610612757,119,1610612749,116,2024-01-31 22:00:00
117088,1629028,Deandre,Ayton,NaN,NaN,1610612757,52,4,4.6,2.8,231,1610612757,119,1610612749,116,2024-01-31 22:00:00
117089,1629028,Deandre,Ayton,NaN,NaN,1610612757,53,4,2.8,2.8,231,1610612757,119,1610612749,116,2024-01-31 22:00:00
117090,1629028,Deandre,Ayton,NaN,NaN,1610612757,54,4,2.8,0.0,231,1610612757,119,1610612749,116,2024-01-31 22:00:00

In [28]:
team_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   teamId         62 non-null     int64
 1   leagueLk       62 non-null     object
 2   teamName       62 non-null     object
 3   teamNameShort  62 non-null     object
 4   teamNickname   62 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.5+ KB

In [32]:

# Merge with teams based on team_id
player_roster_lineup_game_team_df = pd.merge(player_roster_lineup_game_df, team_df, on='teamId', how='left')
player_roster_lineup_game_team_df

,player_id,first_name_x,last_name_x,position,contract_type,teamId,lineup_num,period,time_in,time_out,game_id,home_id,home_score,away_id,away_score,game_date,leagueLk,teamName,teamNameShort,teamNickname
0,1626246,Boban,Marjanovic,NaN,NaN,1610612745,50,4,405.0,405.0,183,1610612766,104,1610612745,138,2024-01-26 19:00:00,NBA,Houston Rockets,HOU,Rockets
1,1626246,Boban,Marjanovic,NaN,NaN,1610612745,51,4,405.0,359.0,183,1610612766,104,1610612745,138,2024-01-26 19:00:00,NBA,Houston Rockets,HOU,Rockets
2,1626246,Boban,Marjanovic,NaN,NaN,1610612745,52,4,359.0,191.0,183,1610612766,104,1610612745,138,2024-01-26 19:00:00,NBA,Houston Rockets,HOU,Rockets
3,1626246,Boban,Marjanovic,NaN,NaN,1610612745,53,4,191.0,0.0,183,1610612766,104,1610612745,138,2024-01-26 19:00:00,NBA,Houston Rockets,HOU,Rockets
4,1626246,Boban,Marjanovic,NaN,NaN,1610612745,47,4,365.0,0.0,3,1610612745,136,1610612765,113,2024-01-01 20:00:00,NBA,Houston Rockets,HOU,Rockets
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117086,1629028,Deandre,Ayton,NaN,NaN,1610612757,50,4,5.6,4.6,231,1610612757,119,1610612749,116,2024-01-31 22:00:00,NBA,Portland Trail Blazers,POR,Trail Blazers
117087,1629028,Deandre,Ayton,NaN,NaN,1610612757,51,4,4.6,4.6,231,1610612757,119,1610612749,116,2024-01-31 22:00:00,NBA,Portland Trail Blazers,POR,Trail Blazers
117088,1629028,Deandre,Ayton,NaN,NaN,1610612757,52,4,4.6,2.8,231,1610612757,119,1610612749,116,2024-01-31 22:00:00,NBA,Portland Trail Blazers,POR,Trail Blazers
117089,1629028,Deandre,Ayton,NaN,NaN,1610612757,53,4,2.8,2.8,231,1610612757,119,1610612749,116,2024-01-31 22:00:00,NBA,Portland Trail Blazers,POR,Trail Blazers
117090,1629028,Deandre,Ayton,NaN,NaN,1610612757,54,4,2.8,0.0,231,1610612757,119,1610612749,116,2024-01-31 22:00:00,NBA,Portland Trail Blazers,POR,Trail Blazers

In [40]:
player_roster_lineup_game_team_df = player_roster_lineup_game_team_df.rename(columns={'teamId': 'nba_teamId'})

In [41]:
player_roster_lineup_game_team_df

,player_id,first_name_x,last_name_x,position,contract_type,nba_teamId,lineup_num,period,time_in,time_out,game_id,home_id,home_score,away_id,away_score,game_date,leagueLk,teamName,teamNameShort,teamNickname
0,1626246,Boban,Marjanovic,NaN,NaN,1610612745,50,4,405.0,405.0,183,1610612766,104,1610612745,138,2024-01-26 19:00:00,NBA,Houston Rockets,HOU,Rockets
1,1626246,Boban,Marjanovic,NaN,NaN,1610612745,51,4,405.0,359.0,183,1610612766,104,1610612745,138,2024-01-26 19:00:00,NBA,Houston Rockets,HOU,Rockets
2,1626246,Boban,Marjanovic,NaN,NaN,1610612745,52,4,359.0,191.0,183,1610612766,104,1610612745,138,2024-01-26 19:00:00,NBA,Houston Rockets,HOU,Rockets
3,1626246,Boban,Marjanovic,NaN,NaN,1610612745,53,4,191.0,0.0,183,1610612766,104,1610612745,138,2024-01-26 19:00:00,NBA,Houston Rockets,HOU,Rockets
4,1626246,Boban,Marjanovic,NaN,NaN,1610612745,47,4,365.0,0.0,3,1610612745,136,1610612765,113,2024-01-01 20:00:00,NBA,Houston Rockets,HOU,Rockets
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117086,1629028,Deandre,Ayton,NaN,NaN,1610612757,50,4,5.6,4.6,231,1610612757,119,1610612749,116,2024-01-31 22:00:00,NBA,Portland Trail Blazers,POR,Trail Blazers
117087,1629028,Deandre,Ayton,NaN,NaN,1610612757,51,4,4.6,4.6,231,1610612757,119,1610612749,116,2024-01-31 22:00:00,NBA,Portland Trail Blazers,POR,Trail Blazers
117088,1629028,Deandre,Ayton,NaN,NaN,1610612757,52,4,4.6,2.8,231,1610612757,119,1610612749,116,2024-01-31 22:00:00,NBA,Portland Trail Blazers,POR,Trail Blazers
117089,1629028,Deandre,Ayton,NaN,NaN,1610612757,53,4,2.8,2.8,231,1610612757,119,1610612749,116,2024-01-31 22:00:00,NBA,Portland Trail Blazers,POR,Trail Blazers
117090,1629028,Deandre,Ayton,NaN,NaN,1610612757,54,4,2.8,0.0,231,1610612757,119,1610612749,116,2024-01-31 22:00:00,NBA,Portland Trail Blazers,POR,Trail Blazers

In [42]:
final_df = pd.merge(player_roster_lineup_game_team_df, team_affiliate_df, on='nba_teamId', how='left')

In [44]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117091 entries, 0 to 117090
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   player_id      117091 non-null  int64
 1   first_name_x   117091 non-null  object
 2   last_name_x    117091 non-null  object
 3   position       7278 non-null    object
 4   contract_type  7278 non-null    object
 5   nba_teamId     117091 non-null  int64
 6   lineup_num     117091 non-null  int64
 7   period         117091 non-null  int64
 8   time_in        117091 non-null  float64
 9   time_out       117091 non-null  float64
 10  game_id        117091 non-null  int64
 11  home_id        117091 non-null  int64
 12  home_score     117091 non-null  int64
 13  away_id        117091 non-null  int64
 14  away_score     117091 non-null  int64
 15  game_date      117091 non-null  object
 16  leagueLk       117091 non-null  object
 17  teamName       117091 non-null  object
 18  teamNameShort  117091 non-null  object
 19  teamNickname   117091 non-null  object
 20  nba_abrv       117091 non-null  object
 21  glg_teamId     113076 non-null  float64
 22  glg_abrv       113076 non-null  object
dtypes: float64(3), int64(9), object(11)
memory usage: 20.5+ MB

In [34]:
team_affiliate_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   nba_teamId  30 non-null     int64
 1   nba_abrv    30 non-null     object
 2   glg_teamId  29 non-null     float64
 3   glg_abrv    29 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 1.1+ KB

In [9]:
# prompt: how can i join the tables together

import pandas as pd
# Merge players and roster based on player_id
player_roster_df = pd.merge(players_df, roster_df, on='player_id', how='left')

# Merge player_roster with lineups based on roster_id
player_roster_lineup_df = pd.merge(player_roster_df, lineups_df, on='roster_id', how='left')

# Merge with games based on game_id
player_roster_lineup_game_df = pd.merge(player_roster_lineup_df, games_df, on='game_id', how='left')

# Merge with teams based on team_id
player_roster_lineup_game_team_df = pd.merge(player_roster_lineup_game_df, team_df, on='teamId', how='left')

# Merge with team_affiliate based on team_id
final_df = pd.merge(player_roster_lineup_game_team_df, team_affiliate_df, on='team_id', how='left')

# Display the final merged DataFrame
final_df

KeyError: 'roster_id'

In [11]:
import sqlite3
conn = sqlite3.connect('lac_fullstack_dev.db')
cursor = conn.cursor()

In [12]:
team_sql = team_df.to_sql('team', conn, if_exists='replace', index=False)

In [13]:
team_affiliate_sql = team_affiliate_df.to_sql('team_affiliate', conn, if_exists='replace', index=False)
games_sql = games_df.to_sql('games', conn, if_exists='replace', index=False)
lineups_sql = lineups_df.to_sql('lineups', conn, if_exists='replace', index=False)
roster_sql = roster_df.to_sql('roster', conn, if_exists='replace', index=False)
players_sql = players_df.to_sql('players', conn, if_exists='replace', index=False)

In [17]:
cursor.execute(" SELECT * FROM team_affiliate")
results = cursor.fetchall()
for row in results:
    print(row)

(1610612737, 'ATL', 1612709929.0, 'CPS')
(1610612751, 'BKN', 1612709921.0, 'LIN')
(1610612738, 'BOS', 1612709915.0, 'MNE')
(1610612766, 'CHA', 1612709922.0, 'GBO')
(1610612741, 'CHI', 1612709923.0, 'WCB')
(1610612739, 'CLE', 1612709893.0, 'CLC')
(1610612742, 'DAL', 1612709918.0, 'TEX')
(1610612743, 'DEN', 1612709917.0, 'GRG')
(1610612765, 'DET', 1612709932.0, 'MCC')
(1610612744, 'GSW', 1612709902.0, 'SCW')
(1610612745, 'HOU', 1612709908.0, 'RGV')
(1610612754, 'IND', 1612709910.0, 'IMA')
(1610612746, 'LAC', 1612709924.0, 'ONT')
(1610612747, 'LAL', 1612709905.0, 'SBL')
(1610612763, 'MEM', 1612709926.0, 'MHU')
(1610612748, 'MIA', 1612709904.0, 'SXF')
(1610612749, 'MIL', 1612709927.0, 'WIS')
(1610612750, 'MIN', 1612709911.0, 'IWA')
(1610612740, 'NOP', 1612709913.0, 'BHM')
(1610612752, 'NYK', 1612709919.0, 'WES')
(1610612760, 'OKC', 1612709889.0, 'OKL')
(1610612753, 'ORL', 1612709925.0, 'OSC')
(1610612755, 'PHI', 1612709909.0, 'DEL')
(1610612756, 'PHX', None, None)
(1610612757, 'POR', 1612709933.0, 'RCR')
(1610612758, 'SAC', 1612709914.0, 'STO')
(1610612759, 'SAS', 1612709890.0, 'AUS')
(1610612761, 'TOR', 1612709920.0, 'RAP')
(1610612762, 'UTA', 1612709903.0, 'SLC')
(1610612764, 'WAS', 1612709928.0, 'CCG')

In [18]:
cursor.execute("SELECT * FROM team_affiliate")
results = cursor.fetchall()
column_names = [desc[0] for desc in cursor.description]

for row in results:
    row_dict = dict(zip(column_names, row))
    print(row_dict)

{'nba_teamId': 1610612737, 'nba_abrv': 'ATL', 'glg_teamId': 1612709929.0, 'glg_abrv': 'CPS'}
{'nba_teamId': 1610612751, 'nba_abrv': 'BKN', 'glg_teamId': 1612709921.0, 'glg_abrv': 'LIN'}
{'nba_teamId': 1610612738, 'nba_abrv': 'BOS', 'glg_teamId': 1612709915.0, 'glg_abrv': 'MNE'}
{'nba_teamId': 1610612766, 'nba_abrv': 'CHA', 'glg_teamId': 1612709922.0, 'glg_abrv': 'GBO'}
{'nba_teamId': 1610612741, 'nba_abrv': 'CHI', 'glg_teamId': 1612709923.0, 'glg_abrv': 'WCB'}
{'nba_teamId': 1610612739, 'nba_abrv': 'CLE', 'glg_teamId': 1612709893.0, 'glg_abrv': 'CLC'}
{'nba_teamId': 1610612742, 'nba_abrv': 'DAL', 'glg_teamId': 1612709918.0, 'glg_abrv': 'TEX'}
{'nba_teamId': 1610612743, 'nba_abrv': 'DEN', 'glg_teamId': 1612709917.0, 'glg_abrv': 'GRG'}
{'nba_teamId': 1610612765, 'nba_abrv': 'DET', 'glg_teamId': 1612709932.0, 'glg_abrv': 'MCC'}
{'nba_teamId': 1610612744, 'nba_abrv': 'GSW', 'glg_teamId': 1612709902.0, 'glg_abrv': 'SCW'}
{'nba_teamId': 1610612745, 'nba_abrv': 'HOU', 'glg_teamId': 1612709908.0, 'glg_abrv': 'RGV'}
{'nba_teamId': 1610612754, 'nba_abrv': 'IND', 'glg_teamId': 1612709910.0, 'glg_abrv': 'IMA'}
{'nba_teamId': 1610612746, 'nba_abrv': 'LAC', 'glg_teamId': 1612709924.0, 'glg_abrv': 'ONT'}
{'nba_teamId': 1610612747, 'nba_abrv': 'LAL', 'glg_teamId': 1612709905.0, 'glg_abrv': 'SBL'}
{'nba_teamId': 1610612763, 'nba_abrv': 'MEM', 'glg_teamId': 1612709926.0, 'glg_abrv': 'MHU'}
{'nba_teamId': 1610612748, 'nba_abrv': 'MIA', 'glg_teamId': 1612709904.0, 'glg_abrv': 'SXF'}
{'nba_teamId': 1610612749, 'nba_abrv': 'MIL', 'glg_teamId': 1612709927.0, 'glg_abrv': 'WIS'}
{'nba_teamId': 1610612750, 'nba_abrv': 'MIN', 'glg_teamId': 1612709911.0, 'glg_abrv': 'IWA'}
{'nba_teamId': 1610612740, 'nba_abrv': 'NOP', 'glg_teamId': 1612709913.0, 'glg_abrv': 'BHM'}
{'nba_teamId': 1610612752, 'nba_abrv': 'NYK', 'glg_teamId': 1612709919.0, 'glg_abrv': 'WES'}
{'nba_teamId': 1610612760, 'nba_abrv': 'OKC', 'glg_teamId': 1612709889.0, 'glg_abrv': 'OKL'}
{'nba_teamId': 1610612753, 'nba_abrv': 'ORL', 'glg_teamId': 1612709925.0, 'glg_abrv': 'OSC'}
{'nba_teamId': 1610612755, 'nba_abrv': 'PHI', 'glg_teamId': 1612709909.0, 'glg_abrv': 'DEL'}
{'nba_teamId': 1610612756, 'nba_abrv': 'PHX', 'glg_teamId': None, 'glg_abrv': None}
{'nba_teamId': 1610612757, 'nba_abrv': 'POR', 'glg_teamId': 1612709933.0, 'glg_abrv': 'RCR'}
{'nba_teamId': 1610612758, 'nba_abrv': 'SAC', 'glg_teamId': 1612709914.0, 'glg_abrv': 'STO'}
{'nba_teamId': 1610612759, 'nba_abrv': 'SAS', 'glg_teamId': 1612709890.0, 'glg_abrv': 'AUS'}
{'nba_teamId': 1610612761, 'nba_abrv': 'TOR', 'glg_teamId': 1612709920.0, 'glg_abrv': 'RAP'}
{'nba_teamId': 1610612762, 'nba_abrv': 'UTA', 'glg_teamId': 1612709903.0, 'glg_abrv': 'SLC'}
{'nba_teamId': 1610612764, 'nba_abrv': 'WAS', 'glg_teamId': 1612709928.0, 'glg_abrv': 'CCG'}